export const categories = [
  { id: 1, name: "Makeup" },
  { id: 2, name: "Skincare" },
  { id: 3, name: "Haircare" },
  { id: 4, name: "Fragrance" },
  { id: 5, name: "Nail Care" },
  { id: 6, name: "Bath & Body" },
  { id: 7, name: "Tools & Brushes" },
  { id: 8, name: "Men's Grooming" },
  { id: 9, name: "Sun Care" },
  { id: 10, name: "Lip Care" },
  { id: 11, name: "Eye Care" },
  { id: 12, name: "Foundation" },
  { id: 13, name: "Lipstick" },
  { id: 14, name: "Mascara" },
  { id: 15, name: "Eyeshadow" },
  { id: 16, name: "Blush" },
  { id: 17, name: "Highlighter" },
  { id: 18, name: "Concealer" },
  { id: 19, name: "Setting Spray" },
  { id: 20, name: "Beauty Tools" },
];